version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=yourCloudflareAPIKey # https://api.cloudflare.com/
      - ZONE=yourdomain.tld
      - SUBDOMAIN=yoursubdomain
      - PROXIED=false
