version: '2'

services:
  proxy:
    image: traefik:v1.7.12-alpine
    command:
      - --configFile=/traefik.toml
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=YourCloudflareEmail@example.com
      - CF_API_KEY=yourCloudflareAPIKey               # https://api.cloudflare.com/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/traefik/traefik.toml:/traefik.toml
      - /data/docker/traefik/acme.json:/acme.json
    # REMOVE this section if you don't want the dashboard/API
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:subdomain.yourdomain.tld"
      - "traefik.port=8080"

networks:
  web:
    external: true
